# Generated by Django 5.1.4 on 2024-12-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesscard",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="businesscard",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
