# Generated by Django 5.1.4 on 2024-12-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_businesscard_first_name_businesscard_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesscard",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
