# Generated by Django 5.1.4 on 2024-12-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_businesscard_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesscard",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="businesscard",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="businesscard",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
