# Generated by Django 5.1.4 on 2025-01-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_businesscard_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscard',
            name='theme',
        ),
    ]
