# Generated by Django 5.1.4 on 2025-01-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_businesscard_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='allow_lead_capture',
            field=models.BooleanField(default=False),
        ),
    ]
