# Generated by Django 5.1.4 on 2025-01-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_businesscard_allow_lead_capture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='allow_lead_capture',
            field=models.BooleanField(default=True),
        ),
    ]
